In [1]:
import cv2
import numpy as np
import pandas as pd

## Read an Image using OpenCV
- cv2.imread('path', flag)
- path of image
- flag:
    1. 0 for grayscale
    2. 1 for color image
    3. -1 for transparent background image

In [2]:
img = cv2.imread('images/doremonGrayScale.jpeg', 0)

print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [3]:
img.shape

(266, 190)

## Display image with openCV
- Read the image [cv2.imread('path', flag)]
- Display the image [imshow('Window namd{random}', var used to read the image)]
- Set waiting time image being on the screen [cv2.waitkey()]
    - 0: waiting for user to press any key
    - 1000: 1second as time is in mili second
- Destroy all windows so it will not affect rest task [cv2.destroyAllWindows()]

In [4]:
# Reading the image
img = cv2.imread('images/doraemon.jpeg', 1)

# Display the Image
cv2.imshow("Image", img)

# Wait for user to press any key
cv2.waitKey(0)

# Destroy the window after any key is pressed
cv2.destroyAllWindows()



## Check image properties
- img.dtype
- img.ndim

In [5]:
img = cv2.imread('images/doraemon.jpeg',1)

print("Data type of image: {}".format(img.dtype))
print("Data type of image: {}".format(img.ndim))

Data type of image: uint8
Data type of image: 3
