In [1]:
import cv2
import numpy as np
import pandas as pd

## Read an Image using OpenCV
- cv2.imread('path', flag)
- path of image
- flag:
    1. 0 for grayscale
    2. 1 for color image
    3. -1 for transparent background image

In [2]:
img = cv2.imread('images/doremonGrayScale.jpeg', 0)

print(img)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [3]:
img.shape

(266, 190)

## Display image with openCV
- Read the image [cv2.imread('path', flag)]
- Display the image [imshow('Window namd{random}', var used to read the image)]
- Set waiting time image being on the screen [cv2.waitkey()]
    - 0: waiting for user to press any key
    - 1000: 1second as time is in mili second
- Destroy all windows so it will not affect rest task [cv2.destroyAllWindows()]

In [4]:
# Reading the image
img = cv2.imread('images/doraemon.jpeg', 1)

# Display the Image
cv2.imshow("Image", img)

# Wait for user to press any key
cv2.waitKey(0)

# Destroy the window after any key is pressed
cv2.destroyAllWindows()



## Check image properties
- img.dtype
- img.ndim

In [5]:
img = cv2.imread('images/doraemon.jpeg',1)

print("Data type of image: {}".format(img.dtype))
print("Data type of image: {}".format(img.ndim))

Data type of image: uint8
Data type of image: 3


## Acess pixel point

In [7]:
print(img[130, 130])

[106 157 237]


## Change Pixel of image

In [ ]:
img[130,130] = 0

## Modify image ROI (Region of Image)

In [8]:
# Make copy of the original image
Img_copy = img.copy()

# Modify the ROI
Img_copy[100:130, 100:130] = 0

#Display Image
cv2.imshow('Modify ROI', Img_copy)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
img = cv2.imread('images/Naruto.jpg', 1)

img.shape

(675, 1200, 3)

## Change image size

In [14]:
img = cv2.imread('images/Naruto.jpg', 1)

# Resizing image to a fixed size 500*500
# resized = cv2.resize(img, (500,500))

# Resize image using percentage to protest ratio of Image
resized = cv2.resize(img, (0,0), fx=.5, fy=.5)

cv2.imshow('Resized image', resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Resize certain dimension (either height or width) and maintain the aspect ratio of other dimension

In [13]:
img = cv2.imread('images/Naruto.jpg', 1)

# Get width and height of image
height, width, channel = img.shape

# Compute ratio of new height
ratio = 500.0/width

# Get the new height
new_height = int(height * ratio)

# Resize image using percentage to protest ratio of Image
resized = cv2.resize(img, (500,new_height))

cv2.imshow('Resized image', resized)
cv2.waitKey(0)
cv2.destroyAllWindows()